### DISCUSSION TITLE
nGrinder 컨트롤러에서 스크립트 생성 시 "Error while saving file to SVN" 에러 질문

### DISCUSSION THREAD

**Discussion by hyeon0208** [naver/ngrinder#980] [Q&A]
현재 Window에서 nGrinder 컨트롤러와 에이전트를 도커 컴포즈로 다운로드 하고 실행시켰고 docker-compose.yml 파일은 다음과 같습니다.
```
version: '3.8'
services:
  controller:
    image: ngrinder/controller
    restart: always
    ports:
      - "80:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder-controller:/opt/ngrinder-controller
  agent:
    image: ngrinder/agent
    restart: always
    links:
      - controller
```
해당 컨테이너 실행 후 localhost:80/login 으로 컨트롤러 로그인 후, "에이전트 관리" 탭에서 에이전트에 초록불이 들어와 있는 것을 확인 했는데, 스크립트 생성 시 "Error while saving file to SVN"에러가 발생했습니다.
![image](https://github.com/naver/ngrinder/assets/99153215/af241b28-8418-4e14-954c-2d0093547838)
(위 그림의 빨간줄 부분은 로컬PC의 IP를 입력했고 포트는 테스트할 애플리케이션 서버가 실행되는 포트를 입력했습니다.)

이 에러를 검색해도 관련 글이 딱 하나 있던데 거기서 말한 방식대로 컨테이너를 종료 후, ngrinder-controller 폴더를 지우고 다시 구동시켜봐도 여전히 동일한 에러가 발생해서 질문 드립니다.
뭐가 문제일까요 ?? 이 에러를 알 기 위해 더 필요한 자료가 있을까요??
